/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nazgultorre
 */
public class AppColorido extends javax.swing.JFrame {

    /**
     * Creates new form AppColorido
     */
    public AppColorido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void exibirJanela(JInternalFrame janela){
    
        //add o objeto na interface
        dtpColorido.add(janela);
        
        //exibindo o objeto
        janela.show();
    
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtpColorido = new javax.swing.JDesktopPane();
        mnbColorido = new javax.swing.JMenuBar();
        mnuPaletaCores = new javax.swing.JMenu();
        mniAmarelo = new javax.swing.JMenuItem();
        mniAzul = new javax.swing.JMenuItem();
        mniVerde = new javax.swing.JMenuItem();
        mniVermelho = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniSair = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("aplicativo colorido");

        javax.swing.GroupLayout dtpColoridoLayout = new javax.swing.GroupLayout(dtpColorido);
        dtpColorido.setLayout(dtpColoridoLayout);
        dtpColoridoLayout.setHorizontalGroup(
            dtpColoridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        dtpColoridoLayout.setVerticalGroup(
            dtpColoridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        mnuPaletaCores.setText("Paleta de cores");

        mniAmarelo.setText("Amarelo");
        mniAmarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAmareloActionPerformed(evt);
            }
        });
        mnuPaletaCores.add(mniAmarelo);

        mniAzul.setText("Azul");
        mniAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAzulActionPerformed(evt);
            }
        });
        mnuPaletaCores.add(mniAzul);

        mniVerde.setText("Verde");
        mniVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVerdeActionPerformed(evt);
            }
        });
        mnuPaletaCores.add(mniVerde);

        mniVermelho.setText("Vermelho");
        mniVermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVermelhoActionPerformed(evt);
            }
        });
        mnuPaletaCores.add(mniVermelho);
        mnuPaletaCores.add(jSeparator1);

        mniSair.setText("Sair");
        mniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSairActionPerformed(evt);
            }
        });
        mnuPaletaCores.add(mniSair);

        mnbColorido.add(mnuPaletaCores);

        mnuAjuda.setText("Ajuda");
        mnbColorido.add(mnuAjuda);

        setJMenuBar(mnbColorido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtpColorido)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dtpColorido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAzulActionPerformed
        // TODO add your handling code here:
        //chamada do objeto exibir janela
        this.exibirJanela(new Azul());
        
        //criação e instancia do objeto da classe azul
        //Azul azul = new Azul();
        
        //add o objeto na interface
        //dtpColorido.add(azul);
        
        //exibindo o objeto
        //azul.show();
    }//GEN-LAST:event_mniAzulActionPerformed

    private void mniVermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVermelhoActionPerformed
        // TODO add your handling code here:
        //chamada do objeto exibir janela
        this.exibirJanela(new Vermelho());
        
        //criação e instancia do objeto da classe vermelho
        //Vermelho vermelho = new Vermelho();
        
        //adcionando o objeto na interface
        //dtpColorido.add(vermelho);
        
        //exibindo o objeto
        //vermelho.show();
    }//GEN-LAST:event_mniVermelhoActionPerformed

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"já vai?","Sair", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                this.dispose();
        }
    }//GEN-LAST:event_mniSairActionPerformed

    private void mniAmareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAmareloActionPerformed
        // TODO add your handling code here:
        //chamada do objeto exibir janela
        this.exibirJanela(new Amarelo());
        
        //criação e instancia do objeto da classe Amarelo
        //Amarelo amarelo = new Amarelo();
        
        //adcionando o objeto na interface
        //dtpColorido.add(amarelo);
        
        //exibindo o objeto
        //amarelo.show();
    }//GEN-LAST:event_mniAmareloActionPerformed

    private void mniVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVerdeActionPerformed
        // TODO add your handling code here:
        //chamada do objeto exibir janela
        this.exibirJanela(new Verde());
        
        //criação e instancia do objeto da classe Verde
        //Verde verde = new Verde();
        
        //adcionando o objeto na interface
        //dtpColorido.add(verde);
        
        //exibindo o objeto
        //verde.show();
    }//GEN-LAST:event_mniVerdeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppColorido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppColorido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppColorido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppColorido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppColorido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dtpColorido;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar mnbColorido;
    private javax.swing.JMenuItem mniAmarelo;
    private javax.swing.JMenuItem mniAzul;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenuItem mniVerde;
    private javax.swing.JMenuItem mniVermelho;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuPaletaCores;
    // End of variables declaration//GEN-END:variables
}
